name: Publish Processing to Clojars

run-name: ${{ github.actor }} published Processing to Clojars

on:
  workflow_dispatch:

jobs:
  publish-processing:
    name: Publish Processing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          bb: latest

      - name: Deploy Processing to Clojars
        run: clojure -T:build build.processing/clojars-release :deploy :remote
        env:
          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}
          CLOJARS_PASSWORD: ${{secrets.CLOJARS_DEPLOY_TOKEN}}

