name: Test

on:
  push:

jobs:
  test-cljs:
    name: Test ClojureScript

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache deps.edn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.cpcache
            ~/.gitlibs
          key: cljs-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: cljs-${{ runner.os }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          bb: latest

      - name: System Info
        run: bb system-info

      # AOT compile applet-listener and applet so CLJS compile can run
      - name: AOT Compile
        run: clojure -T:build aot

      # Only needs to run in one matrix step
      - name: Linting & Formatting
        run: bin/lint

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -Mfig:cljs-test

      - name: Test CLJS Snippet Snapshots
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -M:dev:fig:kaocha cljs-snippets

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: snippet-differences-cljs-${{ runner.os }}-${{ github.sha }}.${{ github.run_attempt }}
          path: |
            dev-resources/snippet-snapshots/*/*/*-actual.png
            dev-resources/snippet-snapshots/*/*/*-difference.png

      - name: Check Advanced Compilation with Release
        run: clojure -T:build build.cljs-advanced-test/advanced-compile

  test-clj:
    name: Test Clojure

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # SEGV on CGLDescribeRenderer after WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
          - macOS-latest
          # Failing because setup-xvfb powershell can't find clojure commands
          # - windows-latest
        java-version: [17] # ,20 to test jdk20

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps.edn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.cpcache
            ~/.gitlibs
          key: clj-${{ runner.os }}-jdk${{ matrix.java-version }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ runner.os }}-jdk${{ matrix.java-version }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
          bb: latest

      - name: System Info
        run: bb system-info

      # AOT compile applet-listener and applet
      - name: AOT Compile
        run: clojure -T:build aot

      # Ie all the tests including snippet tests, many of which are also
      # verified from a CLJS context.
      - name: Test
        uses: coactions/setup-xvfb@v1
        timeout-minutes: 5
        with:
          run: clojure -M:dev:kaocha --reporter doc unit clj-snippets

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: snippet-differences-clj-${{ runner.os }}-${{ github.sha }}.${{ github.run_attempt }}
          path: |
            dev-resources/snippet-snapshots/*/*/*-actual.png
            dev-resources/snippet-snapshots/*/*/*-difference.png
